name: Build Map Editor

on:
  push:
    branches: [ master, tsclient, yr ]
  pull_request:
    branches: [ master, tsclient, yr ]
  workflow_dispatch:
jobs:
  build-editor:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '8.x.x'

    - name: Build Editor
      run: ./build.ps1
      shell: pwsh

    - uses: actions/upload-artifact@v3.1.1
      name: Upload Artifacts
      with:
        name: WorldAlteringEditor
        path: ./Build